### ISSUE TITLE
目测比原版飞机慢很多

### ISSUE THREAD

**Issue by laoyur** [dawei101/shadowsocks-android-java#10]
使用一模一样的线路，原版飞机看油管无压力，用了你的版本，会卡顿，动不动就缓冲，aes-256-cfb
是不是java的效率问题？
不知道如何优化

**Comment by dawei101** [comment]
加密的地方确实会慢，因为加密的代码用的是 bytes[], 如果改成加密运算尽量用buffer的方式（或者把内存使用量固定），加密解密速度会有所提升。

https://github.com/dawei101/shadowsocks-android-java/blob/master/app/src/main/java/com/vm/shadowsocks/tunnel/shadowsocks/ShadowsocksTunnel.java

别的地方我暂时想不到

**Comment by dawei101** [comment]
我也发现这个问题，初步认为是在dns的部分严重拖慢了速度。

本版本的实现在dns的地方做了很大手脚。

要想变快，应该同时将dns 抛给ss server端解析，以加快速度，并得到更好的解析服务器。

**Comment by dawei101** [comment]
经过排查，还真是加密解密的效率问题，争取尽快优化掉。

**Comment by sunqiangcn** [comment]
不能支持多个服务器 每次换服务器都很麻烦 希望解决

**Comment by so898** [comment]
我尝试做了一点简单的线程处理，比如说把线程获取内容的处理等待时间从100ms 下降到1ms，发现效率有所提升，从后台网络速率检测来看，软件在发送和接受数据包的时候都有明显的波状起伏，Shadosocks 官方版本就不存在这样的问题。
刚才我刚按照官方版的思路在这份代码的基础上引入 libss-local libtun2socks 并编译 jnihelper，嫁接过程中我发现官方版在处理从 ss-local 返回的 socket 时使用了数量为4的线程池来不断的获取数据，感觉这种做法对于数据获取的效率有很大帮助。
不过官方版那种从 fd 转 sock 再传递到 ss-local 的做法着实有些蛋疼，但这样让 tun2sock 这边托管了 fd 处理，似乎对效率也有帮助。JNI 在等待 fd 数据的时候似乎比 Java 会更有效率。
关于作者提到的加密，我个人尝试过引用 ss-local 的方法来通过 JNI 加解密，感觉效率提升并没有修改线程池来的大，当然可能是我代码写的太烂了……

**Comment by dawei101** [comment]
据悉，在 @so898 的更新中，用了新版的sdk编译后，速度有极大提升。
v1.2中我也已经把等待处理时间从100ms减到20ms间隔，理论上100ms不是什么瓶颈，因为在活跃网络下很难到sleep，在惰性网络转到活跃网络又不会因为100ms有感知。

大家使用后也请再关注此issue。
