### ISSUE TITLE
Scala版本支持per-app proxy

### ISSUE THREAD

**Issue by Honsec** [dawei101/shadowsocks-android-java#16]
能否支持或者提示一下per-app proxy 功能

**Comment by Honsec** [comment]
实在是无法实现

**Comment by coolspan** [comment]
5.0以上，系统提供接口。5.0以下可以根据ip数据包获取到对应的本地端口号，然后根据端口号获取uid，根据uid可以获取到app，比较麻烦。

**Comment by zgsxdtwyf** [comment]
"5.0以上，系统提供接口。5.0以下可以根据ip数据包获取到对应的本地端口号，然后根据端口号获取uid，根据uid可以获取到app，比较麻烦。" 那我具体该怎么操作呢，求思路，资料解析！

**Comment by so898** [comment]
#30 我之前给版本加上了这个功能，这个 issue 可以关闭了。
