### ISSUE TITLE
好像DNS解析有问题

### ISSUE THREAD

**Issue by ggllcz** [dawei101/shadowsocks-android-java#17]
我这里facebook.com不能访问，twitter客户端很不正常，经常不显示或者很慢。但用其它SS客户端都没有问题。

**Comment by dawei101** [comment]
此版本的原理，实际上阉割了dns的功能

在访问某网站时，通过把所有的域名解析映射成局域网段内的ip，来管理起tunnel来。

也就是如果访问facebook.com ，vpn劫持dns解析，并分配并返回10.0.0.0/255.0.0.0的某个ip，同时vpn将该ip的所有访问都映射到facebook.com的服务器(或者通过shadowsocks服务器)


我没有好好测试使用，确实比其他版的速度上慢很多。
