### ISSUE TITLE
项目导入报错问题 

### ISSUE THREAD

**Issue by justxzm** [dawei101/shadowsocks-android-java#18]

**Comment by justxzm** [comment]
导入了bouncycastle.jar和zxing-integration.jar后解决了import报错问题，但还有代码报错缺少方法和类，该项目是否自定义了第三方包，能否给出该项目的所有第三方包下载链接

**Comment by dawei101** [comment]
没有第三方的包

**Comment by dawei101** [comment]
差点忘了，有二维码支持的包放进去了，其实可以去掉的
还有个json的引进来了
[https://github.com/dawei101/shadowsocks-android-java/blob/master/app/build.gradle](gradle)
