### ISSUE TITLE
关于TCP连接

### ISSUE THREAD

**Issue by chenenyu** [dawei101/shadowsocks-android-java#22]
我看代码里并没有操作tcp的seqNum和ackNum，怎么能保证数据的正确性呢？

**Comment by dawei101** [comment]
没操作怎么建立起tcp连接的呢？

**Comment by dawei101** [comment]
[https://github.com/dawei101/shadowsocks-android-java/blob/ed7d2dac6f38339709b86a3f4b8e7347445932cf/app/src/main/java/com/vm/shadowsocks/tcpip/TCPHeader.java#L64](你是不是找这里)
