### ISSUE TITLE
运行一段时间后无法连接远端了，可能是什么原因。

### ISSUE THREAD

**Issue by 6612172** [dawei101/shadowsocks-android-java#28]
W/System.err: java.net.ConnectException: failed to connect to /180.163.25.149 (port 80): isConnected failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:238)
W/System.err:     at java.nio.SocketChannelImpl.finishConnect(SocketChannelImpl.java:277)
W/System.err:     at com.vm.shadowsocks.tunnel.Tunnel.onConnectable(Tunnel.java:110)
W/System.err:     at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:75)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:223)
W/System.err: 	... 4 more

**Comment by dawei101** [comment]
手机网络断开问题
