### ISSUE TITLE
PAC开关在哪里？

### ISSUE THREAD

**Issue by mabobj** [dawei101/shadowsocks-android-java#3]
我发现这个工具不是全局代理？
那PAC相关的代码在什么位置呢

谢谢

**Comment by dawei101** [comment]
没有使用pac，暂时没有全局选项。
有需要全局翻的场景吗？

**Comment by laoyur** [comment]
> 有需要全局翻的场景吗？

有的，比如你的域名规则覆盖不全，某些漏网的app就用不了了。
作者可以指条明路吗，为了实现全局，怎么改最简单？
