### ISSUE TITLE
What's Wrong

### ISSUE THREAD

**Issue by 3412566455** [dawei101/shadowsocks-android-java#35]
When I work it on  pfdDescriptor = builder.establish() this line,the code throws java.lang.SecurityException: Permission Denial: getIntentSender asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
How can I do ?? thansk

**Comment by 3412566455** [comment]
My phone API level is 21,Lenovo A7600

**Comment by dawei101** [comment]
You should require This permission before run above code
