### ISSUE TITLE
when can add rc4-md5 chcha20 salsa20

### ISSUE THREAD

**Issue by HarrisonShen** [dawei101/shadowsocks-android-java#40]
please add rc4-md5 chcha20 salsa20 thanks

**Comment by dawei101** [comment]
Actually, I would fix bugs if I get time on it. 
Adding new encryption is low priority, as you know, there has already been a factory design in code.

#1

**Comment by HarrisonShen** [comment]
i have implement chacha20 use bouncycastle jar ,bouncycastle jar have rc4Engine but i dont know how to imlement rc4-md5,can you tell me how to implement ,my qq is 355969727 you can add me discuss it,if you have time ,hope you implemnt rc4-md5 thanks

**Comment by dawei101** [comment]
Why not submit your code then?

**Comment by smoochiee** [comment]
ive already added rc4-md5 and chacha20....and change my layout...but i have problem in ui mainactivity..
![screenshot_20170826-011702](https://user-images.githubusercontent.com/30816448/29738991-71733760-8a65-11e7-846a-583eceed0e29.png)

**Comment by HarrisonShen** [comment]
can you give me code the implment of  rc4-md5?

**Comment by smoochiee** [comment]
you have poly?

**Comment by HarrisonShen** [comment]
My qq is 355969727 you can add me discuss it

**Comment by smoochiee** [comment]
https://github.com/lihaolanlhl/shadowsocks-android-java
here it is...what changes you made?

**Comment by smoochiee** [comment]
can you help me?

**Comment by HarrisonShen** [comment]
Now i dont change anything,first i learn it，then if possible i can help you，And when you can add salsa20?

**Comment by smoochiee** [comment]
help me with this im trying to create clear button and setText("");   when i press recent button on my phone the deleted text comes back..what  should i add after settext?

**Comment by HarrisonShen** [comment]
1.You only set Text but the value of java code is not change,please checkout the value is "";
2.when i press recent button on my phone the deleted text comes back ,I think the value is not null，so back  again set the value，Check out the 1

**Comment by HarrisonShen** [comment]
The code value you must clear 
  spf = getSharedPreferences(PREF_NAME, MODE_PRIVATE);
        String name = spf.getString(SERVER_NAME, "");
        String port = spf.getString(REMOTE_PORT, "");
        String password = spf.getString(PASSWORD, "");
        String[] methods = getResources().getStringArray(R.array.encrypt);
        int methodId = spf.getInt(ENCRYPT_METHOD, 0);

        if (!name.isEmpty()) {
            mEditServer.setText(name);
        }
        if (!port.isEmpty()) {
            mEditPort.setText(port);

**Comment by smoochiee** [comment]
already fixed

**Comment by smoochiee** [comment]
you know some code to turn off and on this vpn? with time interval?

**Comment by smoochiee** [comment]
i want to make a button of that

**Comment by HarrisonShen** [comment]
You can use a time task to control turn on or off vpn ,see LocalVpnService.java ,by  IsRunning = false; and disconnectVPN() method ,if you hava some problems ,you can send mail to me ,355969727@qq.com

**Comment by dawei101** [comment]
新发布已加入
