### ISSUE TITLE
更改ss端口号浏览器打开不了之前访问的页面

### ISSUE THREAD

**Issue by HarrisonShen** [dawei101/shadowsocks-android-java#56]
比如打开vpn设置端口51000，1.首先访问youtube,2,断开vpn修改端口号为51001，再点youtube访问不了，必须关闭浏览器再打开才能访问该页面 ,使用影梭翻墙没有这个问题 ，能帮忙看下是什么原因导致的吗

**Comment by dawei101** [comment]
这个跟实现原理有关系，浏览器存在dns解析缓存，重启后重新解析正确域名。
