### ISSUE TITLE
点击连接后，即使没有网也显示连接成功。

### ISSUE THREAD

**Issue by cnsms** [dawei101/shadowsocks-android-java#8]
1.无论密码对错都会提示成功。
2.即便手机没有打开网络也会显示连接成功。
3.怎样判断到底真正连接成功。

**Comment by dawei101** [comment]
1. 密码对错是在vpn service之后的tunnel层做的，没有任何使用shadowsocks的时候，谁都不知道密码对错。
2. 你可以理解为，你连你家路由器，但你家路由器没联网同样可以连上。

shadowsocks协议是一个极其简练的协议，没有连接状态，也不需要判断连接状态。

综上：
如果你非要判断连接成功没，在vpn service开启后，跑一个请求试试就知道。

而且有日志输出到了app内

**Comment by cnsms** [comment]
好的，谢谢。
