### ISSUE TITLE
应用本身的socket被代理

### ISSUE THREAD

**Issue by haoxionga** [dawei101/shadowsocks-android-java#81]
在您的应用的基础下，我自己加入了一些功能，现在实现和服务器的socket通信的时候，开启代理，软件本身与服务器的socket也被代理了，这种问题怎么解决

**Comment by zeizeizeiaaa** [comment]
你好，请问解决了吗

**Comment by zeizeizeiaaa** [comment]
> 在您的应用的基础下，我自己加入了一些功能，现在实现和服务器的socket通信的时候，开启代理，软件本身与服务器的socket也被代理了，这种问题怎么解决

你好，请问解决了吗

**Comment by haoxionga** [comment]
@zeizeizeiaaa 没有，后来换成http请求的方式了
