### ISSUE TITLE
请问下怎么支持NAT方式呢？

### ISSUE THREAD

**Issue by WrBug** [dawei101/shadowsocks-android-java#9]
看了下Scala支持NAT模式，请问下你的项目怎么支持NAT方式呢？需要移植吗？

**Comment by dawei101** [comment]
建议看下：
https://github.com/dawei101/shadowsocks-android-java/blob/master/app/src/main/java/com/vpnmore/shadowsocks/core/LocalVpnService.java#L252

我没看过Scala的NAT模式怎么做的。
