### ISSUE TITLE
请教一下关于安卓vpnservice的问题？

### ISSUE THREAD

**Issue by 068089dy** [dawei101/shadowsocks-android-java#99]
我使用vpnservice截取了指定应用的IP数据，并通过tun2socks转发了tcp和dns报文到socks5服务器，这样做了以后，telegram能正常使用，可是chrome和youtube无法使用，我查看了返回的dns报文，看着也没有什么问题。

**Comment by 068089dy** [comment]
我没有特意区分dns请求，只是把它当成udp报文发送，然后收到数据原模原样返回给vpnservice。

**Comment by changguangsheng** [comment]
> 截取了指定应用的IP数据，并通过tun2socks转发了tcp和dns报文到socks5服务器，这样做了以后，telegram能正常使用，可是chrome和youtube无法使用，我查看了返回的dns报文，看着也没有什么问题。

请问，您是通过tun2socks 转发到socks5服务器的么？那我能不能通过socks转发到本地呢，通过处理数据再转发出去呢？如果转发到本地，那ip是多少呢？会不会还被vpnservice截取呢

**Comment by changguangsheng** [comment]
> 我没有特意区分dns请求，只是把它当成udp报文发送，然后收到数据原模原样返回给vpnservice。

能不能加个联系方式 linyi0430@gmail.com

**Comment by 068089dy** [comment]
> > 截取了指定应用的IP数据，并通过tun2socks转发了tcp和dns报文到socks5服务器，这样做了以后，telegram能正常使用，可是chrome和youtube无法使用，我查看了返回的dns报文，看着也没有什么问题。
> 
> 请问，您是通过tun2socks 转发到socks5服务器的么？那我能不能通过socks转发到本地呢，通过处理数据再转发出去呢？如果转发到本地，那ip是多少呢？会不会还被vpnservice截取呢

通过vpnservice发出去的，也会返回给vpnservice，你可以看看这个https://github.com/wear-underpant-12-times/wear_underpant_android

**Comment by changguangsheng** [comment]
> > > 截取了指定应用的IP数据，并通过tun2socks转发了tcp和dns报文到socks5服务器，这样做了以后，telegram能正常使用，可是chrome和youtube无法使用，我查看了返回的dns报文，看着也没有什么问题。
> > 
> > 
> > 请问，您是通过tun2socks 转发到socks5服务器的么？那我能不能通过socks转发到本地呢，通过处理数据再转发出去呢？如果转发到本地，那ip是多少呢？会不会还被vpnservice截取呢
> 
> 通过vpnservice发出去的，也会返回给vpnservice，你可以看看这个https://github.com/wear-underpant-12-times/wear_underpant_android

感谢
